//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

#if UNITY_ANDROID && !UNITY_EDITOR
public class AndroidUtil
{
    public AndroidUtil ()
    {
    }

    static AndroidJavaObject GetContext()
    {
        // First, obtain the current activity context
        using (var actClass = new AndroidJavaClass("com.unity3d.player.UnityPlayer")) 
        {
            return actClass.GetStatic<AndroidJavaObject>("currentActivity");
        }
    }


    public static bool AreHeadphonesConnected()
    {
        AndroidJavaClass ajc  = new AndroidJavaClass("com.wemolab.unityutilplugin.UtilBridge");
        return ajc.CallStatic<bool>("AreHeadphonesConnected", GetContext());
    }
}
#endif

