using UnityEngine;
using System.Collections;

public class CritterInfoData : MonoBehaviour {
    public GameObject critterObject = null;
    public Transform critterTransform = null;
    public Collider critterCollider = null;
    public LODModelData critterLODData = null;
    public Animation critterAnimation = null;
    public CritterAnimationBase animBase = null;
    public FishAudioData audioData = null;
    public FishBendControllerData critterBendData = null;
    public EyeControllerData critterEyeData = null;
    public SwimIdleData swimIdleData = null;
    public SwimIdleBiteData swimIdleBiteData = null;
    public SwimDisperseData swimDisperseData = null;
    public SwimChaseData swimChaseData = null;
    public SwimSchoolFollowData swimSchoolFollowData = null;
    public SwimTargetedData swimTargetedData = null;
    public SwimToPointData swimToPointData = null;
    public SwimFreefallData swimFreefallData = null;
    public SwimStrafingData swimStrafingData = null;
    public SwimParkingData swimParkingData = null;
    public SwimFreeData swimFreeData = null;
    public SwimPlayerInteractData swimPlayerInteractData = null;
    public SwimPlayerViewData swimPlayerViewData = null;
    public SwimFollowPathData swimFollowPathData = null;
    public SwimScriptGoToPointData swimScriptGoToPointData = null;
    public SwimStrafePlayerData swimStrafePlayerData = null;
    public HoldData holdData = null;
    public DeadData deadData = null;
    public GeneralSpeciesData generalSpeciesData = null;
    public GeneralMotionData generalMotionData = null;
    public InteractionData interactionData = null;
    public ViewportMotionData viewportMotionData = null;
    public CircleAroundObjectData circleAroundObjectData = null;
    public AwarenessCollision awarenessCollision = null;
    public SteeringBase critterSteering = null;
    public BoxCollider critterBoxCollider = null;
    public WemoItemData critterItemData = null;
    public DataItem itemData = null;
}
